name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        description: "Enter image tag (optional)"
        required: false

env:
  IMAGE_NAME: flaskapp

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cat
        run: cat templates/index.html

      - name: Set image tag
        id: set_tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            TAG=${GITHUB_SHA::7}
          else
            TAG=${{ github.event.inputs.tag }}
          fi

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & Push Docker image
        run: |
          docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to NUC via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 25
          script: |

            echo "📁 Moving to project directory"
            cd /home/docker-ce/flaskapp

            echo "📥 Pull latest images from Docker Hub"
            docker compose pull

            echo "🛑 Stopping old containers"
            docker compose down

            echo "🚀 Starting updated containers"
            docker compose up -d --build

            echo "🧹 Cleaning unused Docker resources"
            docker system prune -af

            echo "✅ Deployment successful"
